#request constants
int64 a
int64 b

#request fields

---
#response constants
bool sys_active          # actual data for the system enabled/disabled
float32 sys_voltage      # actual data for the system voltage
float32 sys_current      # actual data for the system amperage
float32 sys_temperature  # actual data for the system temperature