#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
import random

class SupplyParameters:
    # Method contructor
    def __init__(self, enable_output=False, op_mode=0, voltage=0.0, current=0.0, voltage_set_point=0.0, current_set_point=0.0):
        self.enable_output = enable_output
        self.op_mode = op_mode
        self.voltage = voltage
        self.current = current
        self.voltage_set_point = voltage_set_point
        self.current_set_point = current_set_point

    # Changes the power supply of the source
    def set_enable_output(self, enable_output):
        self.enable_output = enable_output
        #self.printStatus()
        if self.enable_output:
            return self.enable_output, "Supple power ON"
        else:
            return self.enable_output, "Supple power OFF"
    
    # Changes the mode supply
    def set_op_mode(self, op_mode):
        self.op_mode = op_mode
        if self.op_mode == 0:
            return self.op_mode, 0
        elif op_mode == 1:
            return self.op_mode, 1
    
    # Changes the supply voltage of the power supply.
    def set_voltage_set_point (self, voltage):
        # Changes the mode supply voltage
        self.set_op_mode(0)
        self.voltage = voltage
        self.voltage_set_point = self.voltage

        # random value generated by the source
        self.voltage = ((random.randrange(0, self.voltage)) + random.random())
        #self.printStatus()

        return self.voltage, "Switch Voltage"

    # Changes the supply voltage of the power supply.
    def set_current_set_point (self, current):
        # Changes the mode supply current
        self.set_op_mode(1)        
        self.current = current
        self.current_set_point = self.current

        # random value generated by the source
        self.current = ((random.randrange(0, self.current)) + random.random())
        #self.printStatus()
             
        return self.current, "Switch Current"

    def printStatus(self):
        print("\nEnable_output : {0}".format(self.enable_output))
        print("Op_mode : {0}".format(self.op_mode))
        print("Voltage_set_point : {0}".format(self.voltage_set_point))
        print("Voltage : {0}".format(self.voltage))
        print("Current_set_point : {0}".format(self.current_set_point))
        print("Current : {0}".format(self.current))
